

services:
  web:
    build: 
      context: ./frontend


  nginx:
    image: nginx
    container_name: nginx_frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/src/static:/usr/share/nginx/html
      - ./daylang.crt:/etc/ssl/daylang/daylang.crt
      - ./daylang.key:/etc/ssl/daylang/daylang.key
    depends_on:
      - web