services:
  web:
    build: ./frontend
    volumes:
      - ./frontend/dist:/sites/daylang/dist
    ports:
      - "3000:3000"


  nginx:
    image: nginx
    container_name: nginx_frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/src/static:/usr/share/nginx/html
    depends_on:
      - web
